// Code generated by protoc-gen-go. DO NOT EDIT.
// source: exec.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExecRequest struct {
	Executable           string   `protobuf:"bytes,1,opt,name=executable,proto3" json:"executable,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Stdin                []byte   `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Env                  []string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecRequest) Reset()         { *m = ExecRequest{} }
func (m *ExecRequest) String() string { return proto.CompactTextString(m) }
func (*ExecRequest) ProtoMessage()    {}
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d737c7315c25422, []int{0}
}

func (m *ExecRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecRequest.Unmarshal(m, b)
}
func (m *ExecRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecRequest.Marshal(b, m, deterministic)
}
func (m *ExecRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecRequest.Merge(m, src)
}
func (m *ExecRequest) XXX_Size() int {
	return xxx_messageInfo_ExecRequest.Size(m)
}
func (m *ExecRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecRequest proto.InternalMessageInfo

func (m *ExecRequest) GetExecutable() string {
	if m != nil {
		return m.Executable
	}
	return ""
}

func (m *ExecRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ExecRequest) GetStdin() []byte {
	if m != nil {
		return m.Stdin
	}
	return nil
}

func (m *ExecRequest) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

type ExecResult struct {
	ReturnCode           int32    `protobuf:"varint,1,opt,name=returnCode,proto3" json:"returnCode,omitempty"`
	Stdout               string   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               string   `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecResult) Reset()         { *m = ExecResult{} }
func (m *ExecResult) String() string { return proto.CompactTextString(m) }
func (*ExecResult) ProtoMessage()    {}
func (*ExecResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d737c7315c25422, []int{1}
}

func (m *ExecResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecResult.Unmarshal(m, b)
}
func (m *ExecResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecResult.Marshal(b, m, deterministic)
}
func (m *ExecResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecResult.Merge(m, src)
}
func (m *ExecResult) XXX_Size() int {
	return xxx_messageInfo_ExecResult.Size(m)
}
func (m *ExecResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExecResult proto.InternalMessageInfo

func (m *ExecResult) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *ExecResult) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *ExecResult) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func init() {
	proto.RegisterType((*ExecRequest)(nil), "gofigure.ExecRequest")
	proto.RegisterType((*ExecResult)(nil), "gofigure.ExecResult")
}

func init() { proto.RegisterFile("exec.proto", fileDescriptor_4d737c7315c25422) }

var fileDescriptor_4d737c7315c25422 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0xe9, 0x76, 0x77, 0x71, 0x47, 0x0f, 0x12, 0x44, 0x72, 0x92, 0xb2, 0x22, 0xf4, 0xd4,
	0x1e, 0x3c, 0x78, 0x57, 0xfc, 0x02, 0x39, 0x8a, 0x97, 0xfe, 0x19, 0xd3, 0x40, 0x4d, 0x74, 0x32,
	0x23, 0xfd, 0xf8, 0x62, 0x52, 0xa1, 0xa7, 0xcc, 0xfb, 0xf1, 0xe0, 0x97, 0x07, 0x80, 0x0b, 0x0e,
	0xcd, 0x17, 0x05, 0x0e, 0xea, 0xc2, 0x86, 0x0f, 0x67, 0x85, 0xf0, 0xec, 0xe0, 0xf2, 0x75, 0xc1,
	0xc1, 0xe0, 0xb7, 0x60, 0x64, 0x75, 0x97, 0x6b, 0xc2, 0x5d, 0x3f, 0xa3, 0x2e, 0xaa, 0xa2, 0x3e,
	0x99, 0x0d, 0x51, 0x0a, 0xf6, 0x1d, 0xd9, 0xa8, 0x77, 0x55, 0x59, 0x9f, 0x4c, 0xba, 0xd5, 0x0d,
	0x1c, 0x22, 0x8f, 0xce, 0xeb, 0xb2, 0x2a, 0xea, 0x2b, 0x93, 0x83, 0xba, 0x86, 0x12, 0xfd, 0x8f,
	0xde, 0xa7, 0xe2, 0xdf, 0x79, 0x7e, 0x07, 0xc8, 0xaa, 0x28, 0x73, 0x32, 0x11, 0xb2, 0x90, 0x7f,
	0x09, 0x63, 0x36, 0x1d, 0xcc, 0x86, 0xa8, 0x5b, 0x38, 0x46, 0x1e, 0x83, 0xb0, 0xde, 0xa5, 0x5f,
	0xac, 0x69, 0xe5, 0x48, 0x94, 0x74, 0x99, 0x23, 0xd1, 0xf3, 0xc3, 0xdb, 0xbd, 0x75, 0x3c, 0x49,
	0xdf, 0x0c, 0xe1, 0xb3, 0xed, 0x66, 0x5c, 0x26, 0xf1, 0xfc, 0xd4, 0xfe, 0x2f, 0x6d, 0xd3, 0xf2,
	0xfe, 0x98, 0x9e, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xab, 0x06, 0x83, 0x0e, 0x01,
	0x00, 0x00,
}
