// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilePath struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilePath) Reset()         { *m = FilePath{} }
func (m *FilePath) String() string { return proto.CompactTextString(m) }
func (*FilePath) ProtoMessage()    {}
func (*FilePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *FilePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilePath.Unmarshal(m, b)
}
func (m *FilePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilePath.Marshal(b, m, deterministic)
}
func (m *FilePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilePath.Merge(m, src)
}
func (m *FilePath) XXX_Size() int {
	return xxx_messageInfo_FilePath.Size(m)
}
func (m *FilePath) XXX_DiscardUnknown() {
	xxx_messageInfo_FilePath.DiscardUnknown(m)
}

var xxx_messageInfo_FilePath proto.InternalMessageInfo

func (m *FilePath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DeleteRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive            bool     `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DeleteRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

type StatResult struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=isDir,proto3" json:"isDir,omitempty"`
	Exists               bool     `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
	Uid                  uint32   `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid                  uint32   `protobuf:"varint,6,opt,name=gid,proto3" json:"gid,omitempty"`
	Owner                string   `protobuf:"bytes,7,opt,name=owner,proto3" json:"owner,omitempty"`
	Group                string   `protobuf:"bytes,8,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatResult) Reset()         { *m = StatResult{} }
func (m *StatResult) String() string { return proto.CompactTextString(m) }
func (*StatResult) ProtoMessage()    {}
func (*StatResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *StatResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatResult.Unmarshal(m, b)
}
func (m *StatResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatResult.Marshal(b, m, deterministic)
}
func (m *StatResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatResult.Merge(m, src)
}
func (m *StatResult) XXX_Size() int {
	return xxx_messageInfo_StatResult.Size(m)
}
func (m *StatResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StatResult.DiscardUnknown(m)
}

var xxx_messageInfo_StatResult proto.InternalMessageInfo

func (m *StatResult) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StatResult) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *StatResult) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *StatResult) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func (m *StatResult) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *StatResult) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *StatResult) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *StatResult) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type FileRequest struct {
	Properties *FileProperties `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	//enum State {
	//  file = 0;
	//  directory = 1;
	//  absent = 2;
	//  symlink = 3;
	//  hardlink = 4;
	//}
	//State state = 2;
	Recursive            bool     `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Touch                bool     `protobuf:"varint,3,opt,name=touch,proto3" json:"touch,omitempty"`
	LinkTarget           string   `protobuf:"bytes,4,opt,name=linkTarget,proto3" json:"linkTarget,omitempty"`
	Content              []byte   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetProperties() *FileProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *FileRequest) GetRecursive() bool {
	if m != nil {
		return m.Recursive
	}
	return false
}

func (m *FileRequest) GetTouch() bool {
	if m != nil {
		return m.Touch
	}
	return false
}

func (m *FileRequest) GetLinkTarget() string {
	if m != nil {
		return m.LinkTarget
	}
	return ""
}

func (m *FileRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type FileProperties struct {
	Path  string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Group string `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	// Everyone gets octal wrong, so only accept strings
	Mode                 string   `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileProperties) Reset()         { *m = FileProperties{} }
func (m *FileProperties) String() string { return proto.CompactTextString(m) }
func (*FileProperties) ProtoMessage()    {}
func (*FileProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4}
}

func (m *FileProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileProperties.Unmarshal(m, b)
}
func (m *FileProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileProperties.Marshal(b, m, deterministic)
}
func (m *FileProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileProperties.Merge(m, src)
}
func (m *FileProperties) XXX_Size() int {
	return xxx_messageInfo_FileProperties.Size(m)
}
func (m *FileProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_FileProperties.DiscardUnknown(m)
}

var xxx_messageInfo_FileProperties proto.InternalMessageInfo

func (m *FileProperties) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileProperties) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *FileProperties) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *FileProperties) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type DirectoryResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryResult) Reset()         { *m = DirectoryResult{} }
func (m *DirectoryResult) String() string { return proto.CompactTextString(m) }
func (*DirectoryResult) ProtoMessage()    {}
func (*DirectoryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{5}
}

func (m *DirectoryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryResult.Unmarshal(m, b)
}
func (m *DirectoryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryResult.Marshal(b, m, deterministic)
}
func (m *DirectoryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryResult.Merge(m, src)
}
func (m *DirectoryResult) XXX_Size() int {
	return xxx_messageInfo_DirectoryResult.Size(m)
}
func (m *DirectoryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryResult.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryResult proto.InternalMessageInfo

type FileResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileResult) Reset()         { *m = FileResult{} }
func (m *FileResult) String() string { return proto.CompactTextString(m) }
func (*FileResult) ProtoMessage()    {}
func (*FileResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{6}
}

func (m *FileResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileResult.Unmarshal(m, b)
}
func (m *FileResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileResult.Marshal(b, m, deterministic)
}
func (m *FileResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileResult.Merge(m, src)
}
func (m *FileResult) XXX_Size() int {
	return xxx_messageInfo_FileResult.Size(m)
}
func (m *FileResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FileResult.DiscardUnknown(m)
}

var xxx_messageInfo_FileResult proto.InternalMessageInfo

type DeleteResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResult) Reset()         { *m = DeleteResult{} }
func (m *DeleteResult) String() string { return proto.CompactTextString(m) }
func (*DeleteResult) ProtoMessage()    {}
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{7}
}

func (m *DeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResult.Unmarshal(m, b)
}
func (m *DeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResult.Marshal(b, m, deterministic)
}
func (m *DeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResult.Merge(m, src)
}
func (m *DeleteResult) XXX_Size() int {
	return xxx_messageInfo_DeleteResult.Size(m)
}
func (m *DeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FilePath)(nil), "gofigure.FilePath")
	proto.RegisterType((*DeleteRequest)(nil), "gofigure.DeleteRequest")
	proto.RegisterType((*StatResult)(nil), "gofigure.StatResult")
	proto.RegisterType((*FileRequest)(nil), "gofigure.FileRequest")
	proto.RegisterType((*FileProperties)(nil), "gofigure.FileProperties")
	proto.RegisterType((*DirectoryResult)(nil), "gofigure.DirectoryResult")
	proto.RegisterType((*FileResult)(nil), "gofigure.FileResult")
	proto.RegisterType((*DeleteResult)(nil), "gofigure.DeleteResult")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0x95, 0x4d, 0xb7, 0x9b, 0xcc, 0xb6, 0x05, 0x2c, 0x84, 0x7c, 0x40, 0x55, 0x15, 0x84,
	0xd4, 0x53, 0x2a, 0xc1, 0x01, 0xae, 0xa0, 0x8a, 0x33, 0x32, 0x9c, 0xb8, 0xa5, 0xc9, 0x34, 0xb1,
	0x48, 0xe3, 0x60, 0x8f, 0xa1, 0xf0, 0xb3, 0x90, 0xf8, 0x7f, 0xc8, 0x13, 0xd2, 0x16, 0xa9, 0xda,
	0x53, 0xe6, 0xbd, 0xd8, 0x63, 0xcf, 0xf7, 0x0c, 0xb0, 0xd7, 0x2d, 0xe6, 0xbd, 0x35, 0x64, 0x44,
	0x52, 0x9b, 0xbd, 0xae, 0xbd, 0xc5, 0x6c, 0x09, 0xc9, 0x07, 0xdd, 0xe2, 0xc7, 0x82, 0x1a, 0x21,
	0x60, 0xd2, 0x17, 0xd4, 0xc8, 0x68, 0x15, 0xad, 0x53, 0xc5, 0x75, 0xf6, 0x0e, 0xe6, 0x5b, 0x6c,
	0x91, 0x50, 0xe1, 0x37, 0x8f, 0x8e, 0xae, 0x2d, 0x12, 0xcf, 0x21, 0xb5, 0x58, 0x7a, 0xeb, 0xf4,
	0x77, 0x94, 0x37, 0xab, 0x68, 0x9d, 0xa8, 0xb3, 0x91, 0xfd, 0x8e, 0x00, 0x3e, 0x51, 0x41, 0x0a,
	0x9d, 0x6f, 0xb9, 0x81, 0xd3, 0xbf, 0x90, 0x1b, 0xc4, 0x8a, 0xeb, 0xe0, 0x1d, 0x4c, 0x35, 0xec,
	0x4d, 0x15, 0xd7, 0xe2, 0x29, 0xdc, 0x6a, 0xb7, 0xd5, 0x56, 0xc6, 0xdc, 0x70, 0x10, 0xe2, 0x19,
	0x4c, 0xf1, 0xa8, 0x1d, 0x39, 0x39, 0x61, 0xfb, 0x9f, 0x12, 0x8f, 0x21, 0xf6, 0xba, 0x92, 0xb7,
	0xab, 0x68, 0x3d, 0x57, 0xa1, 0x0c, 0x4e, 0xad, 0x2b, 0x39, 0x1d, 0x9c, 0x5a, 0x57, 0xa1, 0xa3,
	0xf9, 0xd1, 0xa1, 0x95, 0x77, 0x7c, 0xcc, 0x20, 0x82, 0x5b, 0x5b, 0xe3, 0x7b, 0x99, 0x0c, 0x2e,
	0x8b, 0xec, 0x4f, 0x04, 0xf7, 0x01, 0xcc, 0x38, 0xf6, 0x5b, 0x80, 0xde, 0x9a, 0x1e, 0x2d, 0x69,
	0x74, 0x7c, 0xf7, 0xfb, 0x57, 0x32, 0x1f, 0x31, 0xe6, 0xcc, 0xf0, 0xf4, 0x5f, 0x5d, 0xac, 0x7d,
	0x18, 0x4e, 0x38, 0x9d, 0x8c, 0x2f, 0x9b, 0x71, 0x4a, 0x16, 0x62, 0x09, 0xd0, 0xea, 0xee, 0xeb,
	0xe7, 0xc2, 0xd6, 0x48, 0x3c, 0x69, 0xaa, 0x2e, 0x1c, 0x21, 0xe1, 0xae, 0x34, 0x1d, 0x61, 0x47,
	0x3c, 0xf1, 0x4c, 0x8d, 0x32, 0xab, 0x60, 0xf1, 0xff, 0x5d, 0xae, 0x06, 0x76, 0x22, 0x71, 0x73,
	0x95, 0x44, 0x7c, 0x41, 0xe2, 0x94, 0xcd, 0xe4, 0x9c, 0x4d, 0xf6, 0x04, 0x1e, 0x6d, 0xb5, 0xc5,
	0x92, 0x8c, 0xfd, 0x39, 0xc4, 0x9a, 0xcd, 0x00, 0x06, 0x5e, 0xac, 0x16, 0x30, 0x1b, 0x9f, 0x4d,
	0xd0, 0xef, 0x5f, 0x7e, 0x79, 0x51, 0x6b, 0x6a, 0xfc, 0x2e, 0x2f, 0xcd, 0x61, 0x53, 0xb4, 0x78,
	0x6c, 0x7c, 0x47, 0x6f, 0x36, 0x23, 0xc0, 0x0d, 0xbf, 0xcb, 0xdd, 0x94, 0x3f, 0xaf, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xd0, 0x89, 0x57, 0x55, 0xac, 0x02, 0x00, 0x00,
}
